NotiflyTestApp/NotiflyTestApp.xcodeproj/project.pbxproj
notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Infrastructures/API/NotiflyAPI+Request.swift
notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Infrastructures/API/NotiflyAPI.swift
notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Infrastructures/Notifications/NotificationsManager.swift
notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Infrastructures/Tracking/TrackingEvent.swift
notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Infrastructures/Tracking/TrackingManager.swift

api request body construct

---

notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Infrastructures/InAppMessage/InAppMessageManager.swift
notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Infrastructures/InAppMessage/WebViewModalViewController.swift

hide in app message

---

CHANGELOG.md
NotiflyTestApp/NotiflyTestApp/SourceCodes/UI/AppDelegate.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Infrastrucutres/InAppMessage/Campaign.swift

chore: create CHALLENGELOG.md

---

Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Infrastrucutres/Notifications/NotificationsManager.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Infrastrucutres/Tracking/TrackingManager.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/NotiflyExtension/NotificationServiceExtension.swift

feat: implement for urgent event logging

feat: implement for urgent event logging

---

Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Infrastrucutres/InAppMessage/InAppMessageManager.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Infrastrucutres/InAppMessage/WebViewModalViewController.swift

feat: check the modal is already disappeared before show in app popup

---

NotiflyTestApp/NotiflyTestApp/SourceCodes/UI/TrackingTestViewController.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Infrastrucutres/InAppMessage/InAppMessageManager.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Infrastrucutres/InAppMessage/WebViewModalViewController.swift

feat: validation if the modal is alreday appeared  @edenkim00

---

CHANGELOG.md
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Infrastrucutres/Notifications/NotificationsManager.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/NotiflyUtil/Constants.swift
notifly_sdk.podspec

feat: add .list option to the default foreground push notification presentation options

---

Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk.xcodeproj/project.pbxproj
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/PrivacyInfo.xcprivacy

feat: add privacy manifest file

---

CHANGELOG.md
NotiflyTestApp/NotiflyTestApp/SourceCodes/UI/AppDelegate.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Infrastructures/Auth/Auth.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Infrastructures/InAppMessage/InAppMessageManager.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Infrastructures/InAppMessage/UserStateManager.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Infrastructures/Tracking/TrackingManager.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Notifly/Notifly.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/NotiflyUtil/Constants.swift
notifly_sdk.podspec

fix: Defending against crashes due to concurrency issues in the process of storing cancellable events.

---

CHANGELOG.md
NotiflyTestApp/NotiflyTestApp/SourceCodes/UI/UserSettingsTestViewController.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk.xcodeproj/project.pbxproj
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Infrastructures/Tracking/TrackingManager.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Notifly/Notifly+PublicAPI.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/NotiflyUtil/Constants.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/NotiflyUtil/Timezone.swift
notifly_sdk.podspec

- Feature: Add `setTimezone`, `setPhoneNumber`, `setEmail` for convenience.
- Feature: Now SDK automatically tracks the user's timezone for device property.

feat: add timezone logging

---

CHANGELOG.md
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Infrastructures/InAppMessage/WebViewModalViewController.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Infrastructures/Notifications/NotificationsManager.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/NotiflyUtil/Constants.swift
notifly_sdk.podspec

chore: fix main thread bug

---

CHANGELOG.md
NotiflyTestApp/NotiflyTestApp/SourceCodes/UI/AppDelegate.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Notifly/Notifly+Helper.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Notifly/Notifly+PublicAPI.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Notifly/Notifly.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/NotiflyExtension/NotificationServiceExtension.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/NotiflyUtil/Constants.swift
deploy.sh
notifly_sdk.podspec
notifly_sdk_push_extension.podspec

feat: separate push extension

---

.swift-format
.swiftlint.yml
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Infrastructures/InAppMessage/Campaign.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Infrastructures/InAppMessage/InAppMessage+Constant.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Infrastructures/InAppMessage/InAppMessageManager.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Infrastructures/InAppMessage/SegmentationHelper.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Infrastructures/InAppMessage/UserState+Constant.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Infrastructures/InAppMessage/UserStateManager.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Infrastructures/InAppMessage/WebViewModalViewController.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Infrastructures/Notifications/NotificationsManager.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Infrastructures/Tracking/TrackingManager.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Infrastructures/User/UserManager.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Notifly/Notifly+Helper.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Notifly/Notifly+PublicAPI.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Notifly/Notifly.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/NotiflyExtension/NotificationServiceExtension.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/NotiflyExtension/NotiflyExtensionAPI.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/NotiflyUtil/AppHelper.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/NotiflyUtil/AsyncWorker.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/NotiflyUtil/Constants.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/NotiflyUtil/Logger.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/NotiflyUtil/MessageData.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/NotiflyUtil/NotiflyCustomUserDefaults.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/NotiflyUtil/Timezone.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/NotiflyUtil/TrackingEvent.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/NotiflyUtil/UUID+.swift

chore: Formatting

---

NotiflyTestApp/NotiflyTestApp.xcodeproj/project.pbxproj
NotiflyTestApp/NotiflyTestApp/SourceCodes/UI/AppDelegate.swift
NotiflyTestApp/NotiflyTestApp/SourceCodes/UI/TrackingTestViewController.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk.xcodeproj/project.pbxproj
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Infrastructures/InAppMessage/Campaign.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Infrastructures/InAppMessage/InAppMessageManager.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Infrastructures/InAppMessage/SegmentationHelper.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Infrastructures/InAppMessage/UserState+Constant.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Infrastructures/InAppMessage/UserStateManager.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Infrastructures/InAppMessage/WebViewModalViewController.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Infrastructures/Tracking/TrackingManager.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Infrastructures/User/UserManager.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Notifly/Notifly+Helper.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Notifly/Notifly+PublicAPI.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/NotiflyExtension/NotificationServiceExtension.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/NotiflyUtil/AnyCodable.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/NotiflyUtil/AppHelper.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/NotiflyUtil/Constants.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/NotiflyUtil/TrackingEvent.swift

feat: Any codable

---

CHANGELOG.md
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Infrastructures/InAppMessage/Campaign.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/NotiflyUtil/Constants.swift
notifly_sdk.podspec
notifly_sdk_push_extension.podspec

feat: support user metadata condition for in app message campaign

---

CHANGELOG.md
NotiflyTestApp/NotiflyTestApp/SourceCodes/UI/AppDelegate.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Infrastructures/Tracking/TrackingManager.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/NotiflyExtension/NotificationServiceExtension.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/NotiflyUtil/Constants.swift
notifly_sdk.podspec
notifly_sdk_push_extension.podspec

chore: change event tracking partition key as notifly device id

---

CHANGELOG.md
Package.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/NotiflyUtil/Constants.swift
notifly_sdk.podspec
notifly_sdk_push_extension.podspec

* update firebase latest version 12.0.0

feat: update firebase latest version

---

.github/workflows/release.yml
.gitignore
CHANGELOG.md

* Changelog 기반 release workflow 추가

feat: add release workflow

---

.github/pull_request_template.md
.github/workflows/ci.yml
NotiflyTestApp/NotiflyNotificationExtension/NotificationService.swift
NotiflyTestApp/NotiflyTestApp/SourceCodes/UI/MainViewController.swift
NotiflyTestApp/NotiflyTestApp/SourceCodes/UI/UserSettingsTestViewController.swift
NotiflyTestApp/NotiflyTestApp/SourceCodes/UI/Util/KeyValueDataInputViewController.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Infrastructures/API/NotiflyAPI+Request.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Infrastructures/API/NotiflyAPI.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Infrastructures/InAppMessage/UserState+Constant.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Infrastructures/User/UserManager.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/NotiflyUtil/AppHelper.swift

feat: add ci workflow

---

.github/workflows/ci.yml

- CI Workflow를 pull request 에서만 동작하도록 수정합니다.
- JIRA ticket : https://greyboxhq.atlassian.net/browse/NOTIFLY-2533

feat: disable ci workflow on push

---

.github/workflows/release.yml

- Cocoapods Setup Step 추가
- JIRA ticket : https://greyboxhq.atlassian.net/browse/NOTIFLY-2533

feat: add cocoapods setup step

---

.github/workflows/release.yml

- Release workflow의 runner를 macos로 변경.
- JIRA ticket : https://greyboxhq.atlassian.net/browse/NOTIFLY-2533

feat: change release actions runner

---

.github/workflows/release.yml

- inputs.skip_cocoapods의 기본값이 제대로 전달되지 않는 이슈 수정

fix: fix invalid input handling

---

notifly_sdk_push_extension.podspec

- push extension의 버전을 sdk버전과 일치 시킵니다.

feat: sync push extension version to sdk version

---

notifly_sdk.podspec
notifly_sdk_push_extension.podspec

- PrivacyInfo.xcprivacy pod files에서 삭제

feat: remove privacy info file

---

notifly_sdk.podspec
notifly_sdk_push_extension.podspec

- xcprivacy 파일 resource로 포함하도록 수정

feat: adjust source code including config

---

notifly_sdk.podspec

- 파일을 PrivacyInfo.xcprivacy resource_bundles 로 수정

feat: adjust resource bundles config

---

notifly_sdk.podspec
notifly_sdk_push_extension.podspec

feat: change PrivacyInfo.xcprivacy path

---

CHANGELOG.md
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/Infrastructures/InAppMessage/WebViewModalViewController.swift
Sources/Notifly/notifly-ios-sdk/notifly-ios-sdk/SourceCodes/NotiflyUtil/Constants.swift
notifly_sdk.podspec
notifly_sdk_push_extension.podspec

- data-export의 message data를 추가하기 위해 in_app_message_show 발생 시, event params에 template name을 추가합니다.
- JIRA ticket : https://greyboxhq.atlassian.net/browse/NOTIFLY-3973
-

feat: add template name to in_app_message_show
